alias: Irrigation
description: ""
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.allotment_water
  - delay: >
      {#---------USER DEFINED PARAMETERS---------#} {# Seconds of watering to
      achieve 10 mm #} {% set baselineSeconds = 100 %} {% if
      states('sensor.openweathermap_temperature')|float < 25 %} {# Normal
      precipitation in mm #} {% set neededPrecip = 10 %} {% else %} {# Hot day
      precipitation in mm #} {% set neededPrecip = 15 %} {% endif %}

      {# Request precipitation #} {% set precip =
      states('sensor.openweathermap_forecast_precipitation')| float%} {#
      Calculate needed precipitation fraction  #} {% set precipNeededFraction =
      1 - (precip / neededPrecip) %} {# Calculate needed seconds to achieve
      needed precipitation  #} {% set precipNeededSeconds =
      ((precipNeededFraction * neededPrecip )| round(0) * baselineSeconds) /10 
      %} {# If needed seconds are above 0, pass needed seconds   #} {% if
      precipNeededSeconds > 0 %} {{ precipNeededSeconds }} {# If needed seconds
      are below 0, pass 0  #} {% else %} 0 {% endif %}
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.allotment_water
mode: single
